// Code generated by ent, DO NOT EDIT.

package googleoauthtoken

const (
	// Label holds the string label denoting the googleoauthtoken type in the database.
	Label = "google_oauth_token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRefreshToken holds the string denoting the refresh_token field in the database.
	FieldRefreshToken = "refresh_token"
	// FieldAccessToken holds the string denoting the access_token field in the database.
	FieldAccessToken = "access_token"
	// FieldExpiry holds the string denoting the expiry field in the database.
	FieldExpiry = "expiry"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the googleoauthtoken in the database.
	Table = "google_oauth_tokens"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "google_oauth_tokens"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for googleoauthtoken fields.
var Columns = []string{
	FieldID,
	FieldRefreshToken,
	FieldAccessToken,
	FieldExpiry,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "google_oauth_tokens"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_id",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
