// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/scarlet0725/prism-api/ent/externalcalendar"
	"github.com/scarlet0725/prism-api/ent/predicate"
)

// ExternalCalendarDelete is the builder for deleting a ExternalCalendar entity.
type ExternalCalendarDelete struct {
	config
	hooks    []Hook
	mutation *ExternalCalendarMutation
}

// Where appends a list predicates to the ExternalCalendarDelete builder.
func (ecd *ExternalCalendarDelete) Where(ps ...predicate.ExternalCalendar) *ExternalCalendarDelete {
	ecd.mutation.Where(ps...)
	return ecd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ecd *ExternalCalendarDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, ExternalCalendarMutation](ctx, ecd.sqlExec, ecd.mutation, ecd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ecd *ExternalCalendarDelete) ExecX(ctx context.Context) int {
	n, err := ecd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ecd *ExternalCalendarDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: externalcalendar.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: externalcalendar.FieldID,
			},
		},
	}
	if ps := ecd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ecd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ecd.mutation.done = true
	return affected, err
}

// ExternalCalendarDeleteOne is the builder for deleting a single ExternalCalendar entity.
type ExternalCalendarDeleteOne struct {
	ecd *ExternalCalendarDelete
}

// Exec executes the deletion query.
func (ecdo *ExternalCalendarDeleteOne) Exec(ctx context.Context) error {
	n, err := ecdo.ecd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{externalcalendar.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ecdo *ExternalCalendarDeleteOne) ExecX(ctx context.Context) {
	ecdo.ecd.ExecX(ctx)
}
