// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/scarlet0725/prism-api/ent/googleoauthtoken"
	"github.com/scarlet0725/prism-api/ent/user"
)

// GoogleOauthToken is the model entity for the GoogleOauthToken schema.
type GoogleOauthToken struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RefreshToken holds the value of the "refresh_token" field.
	RefreshToken string `json:"refresh_token,omitempty"`
	// AccessToken holds the value of the "access_token" field.
	AccessToken string `json:"access_token,omitempty"`
	// Expiry holds the value of the "expiry" field.
	Expiry time.Time `json:"expiry,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GoogleOauthTokenQuery when eager-loading is set.
	Edges   GoogleOauthTokenEdges `json:"edges"`
	user_id *int
}

// GoogleOauthTokenEdges holds the relations/edges for other nodes in the graph.
type GoogleOauthTokenEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GoogleOauthTokenEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GoogleOauthToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case googleoauthtoken.FieldID:
			values[i] = new(sql.NullInt64)
		case googleoauthtoken.FieldRefreshToken, googleoauthtoken.FieldAccessToken:
			values[i] = new(sql.NullString)
		case googleoauthtoken.FieldExpiry:
			values[i] = new(sql.NullTime)
		case googleoauthtoken.ForeignKeys[0]: // user_id
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type GoogleOauthToken", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GoogleOauthToken fields.
func (got *GoogleOauthToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case googleoauthtoken.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			got.ID = int(value.Int64)
		case googleoauthtoken.FieldRefreshToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token", values[i])
			} else if value.Valid {
				got.RefreshToken = value.String
			}
		case googleoauthtoken.FieldAccessToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token", values[i])
			} else if value.Valid {
				got.AccessToken = value.String
			}
		case googleoauthtoken.FieldExpiry:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expiry", values[i])
			} else if value.Valid {
				got.Expiry = value.Time
			}
		case googleoauthtoken.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_id", value)
			} else if value.Valid {
				got.user_id = new(int)
				*got.user_id = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryUser queries the "user" edge of the GoogleOauthToken entity.
func (got *GoogleOauthToken) QueryUser() *UserQuery {
	return (&GoogleOauthTokenClient{config: got.config}).QueryUser(got)
}

// Update returns a builder for updating this GoogleOauthToken.
// Note that you need to call GoogleOauthToken.Unwrap() before calling this method if this GoogleOauthToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (got *GoogleOauthToken) Update() *GoogleOauthTokenUpdateOne {
	return (&GoogleOauthTokenClient{config: got.config}).UpdateOne(got)
}

// Unwrap unwraps the GoogleOauthToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (got *GoogleOauthToken) Unwrap() *GoogleOauthToken {
	_tx, ok := got.config.driver.(*txDriver)
	if !ok {
		panic("ent: GoogleOauthToken is not a transactional entity")
	}
	got.config.driver = _tx.drv
	return got
}

// String implements the fmt.Stringer.
func (got *GoogleOauthToken) String() string {
	var builder strings.Builder
	builder.WriteString("GoogleOauthToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", got.ID))
	builder.WriteString("refresh_token=")
	builder.WriteString(got.RefreshToken)
	builder.WriteString(", ")
	builder.WriteString("access_token=")
	builder.WriteString(got.AccessToken)
	builder.WriteString(", ")
	builder.WriteString("expiry=")
	builder.WriteString(got.Expiry.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GoogleOauthTokens is a parsable slice of GoogleOauthToken.
type GoogleOauthTokens []*GoogleOauthToken

func (got GoogleOauthTokens) config(cfg config) {
	for _i := range got {
		got[_i].config = cfg
	}
}
